#!/bin/sh
set -e
PROJECT_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

GPUS="0"
DATASETS="ogbl-citation2"
MODELS=""
RUNS="1"
HEURISTICS="all"
SPLIT="test"
TEST_POSITIVE_CAP="100000"
COMPUTE_AUC="no"

EVALUATOR_MODULE="eval_modes.full_graph_mode"
CANDIDATE_POLICY="exhaustive"
EVALUATION_LABEL="full_graph"
SELECTOR_POLICY=""
SELECTOR_CHECKPOINT_MODEL=""
SELECTOR_CHECKPOINT_ROOT=""
SELECTOR_CHECKPOINT_RUN=""
TARGET_CHECKPOINT_MODE="heart"
EVAL_CAP="checkpoint"
DATA_ROOT="dataset"
CHECKPOINT_ROOT="checkpoints"
PLANETOID_INPUT_ROOT=""
EDGE_BATCH_SIZE="0"
NODE_CHUNK_SIZE="0"
COMPARISON_BATCH_SIZE="256"
SOURCE_BATCH_SIZE=""
EXTRA_ARGS=""
QUIET="0"
DRY_RUN="0"
POLL_SECONDS="1"

STAMP="$(date +%Y%m%d_%H%M%S)_$$"
LOG_ROOT="$PROJECT_ROOT/logs/full_graph_4gpu/$STAMP"

export GPUS DATASETS MODELS RUNS HEURISTICS SPLIT TEST_POSITIVE_CAP COMPUTE_AUC
export EVALUATOR_MODULE CANDIDATE_POLICY EVALUATION_LABEL SELECTOR_POLICY SELECTOR_CHECKPOINT_MODEL SELECTOR_CHECKPOINT_ROOT SELECTOR_CHECKPOINT_RUN TARGET_CHECKPOINT_MODE
export EVAL_CAP DATA_ROOT CHECKPOINT_ROOT PLANETOID_INPUT_ROOT
export EDGE_BATCH_SIZE NODE_CHUNK_SIZE COMPARISON_BATCH_SIZE SOURCE_BATCH_SIZE EXTRA_ARGS QUIET DRY_RUN POLL_SECONDS LOG_ROOT
exec bash "$PROJECT_ROOT/scripts/evaluator_batch.sh" "$@"
