#!/bin/sh
set -e
PROJECT_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

GPUS="0 1 2 3"
DATASETS="facebook"
MODELS="mf mlp ppr concat gcn gat sage gae seal buddy neo-gnn ncn ncnc nbfnet peg lpformer n2v"
RUNS="1 2 3 4 5"
LEARNEDFEAT_SELECTOR_DEPTHS="2"
LEARNEDFEAT_SELECTOR_HIDDEN_CHANNELS="256"
LEARNEDFEAT_SELECTOR_DROPOUTS="0.1"
LEARNEDFEAT_SELECTOR_LEARNING_RATES="0.01"
LEARNEDFEAT_SELECTOR_WEIGHT_DECAYS="0"
HEURISTICS="all"
SPLIT="test"
TEST_POSITIVE_CAP="100000"

EVALUATOR_MODULE="eval_modes.learnedfeat_mode"
SELECTOR_POLICY="learnedfeat"
CANDIDATE_POLICY="$SELECTOR_POLICY"
EVALUATION_LABEL="$SELECTOR_POLICY"
SELECTOR_CHECKPOINT_MODEL=""
SELECTOR_NEGATIVES="500"
SELECTOR_SCORE_BATCH_SIZE="65536"
SELECTOR_SEED="0"
SELECTOR_EPOCHS="500"
SELECTOR_EVAL_STEPS="5"
SELECTOR_PATIENCE="10"
SELECTOR_BATCH_SIZE="1024"
SELECTOR_METRIC=""
DATA_ROOT="dataset"
CHECKPOINT_ROOT="checkpoints"
TARGET_CHECKPOINT_MODE="heart"
EDGE_BATCH_SIZE="0"
NODE_CHUNK_SIZE="0"
COMPARISON_BATCH_SIZE="256"
SOURCE_BATCH_SIZE=""
QUIET="0"
DRY_RUN="0"
POLL_SECONDS="1"

STAMP="$(date +%Y%m%d_%H%M%S)_$$"
export GPUS DATASETS MODELS RUNS HEURISTICS SPLIT TEST_POSITIVE_CAP
export EVALUATOR_MODULE CANDIDATE_POLICY EVALUATION_LABEL SELECTOR_POLICY SELECTOR_CHECKPOINT_MODEL TARGET_CHECKPOINT_MODE
export SELECTOR_NEGATIVES SELECTOR_SCORE_BATCH_SIZE SELECTOR_SEED SELECTOR_EPOCHS SELECTOR_EVAL_STEPS SELECTOR_PATIENCE SELECTOR_BATCH_SIZE SELECTOR_METRIC
export DATA_ROOT CHECKPOINT_ROOT EDGE_BATCH_SIZE NODE_CHUNK_SIZE COMPARISON_BATCH_SIZE SOURCE_BATCH_SIZE QUIET DRY_RUN POLL_SECONDS
for SELECTOR_DEPTH in $LEARNEDFEAT_SELECTOR_DEPTHS
do
  for SELECTOR_HIDDEN_CHANNELS in $LEARNEDFEAT_SELECTOR_HIDDEN_CHANNELS
  do
    for SELECTOR_DROPOUT in $LEARNEDFEAT_SELECTOR_DROPOUTS
    do
      for SELECTOR_LEARNING_RATE in $LEARNEDFEAT_SELECTOR_LEARNING_RATES
      do
        for SELECTOR_WEIGHT_DECAY in $LEARNEDFEAT_SELECTOR_WEIGHT_DECAYS
        do
          DESIGN_TAG="selector_depth_$SELECTOR_DEPTH"_"hidden_$SELECTOR_HIDDEN_CHANNELS"_"dropout_$SELECTOR_DROPOUT"_"lr_$SELECTOR_LEARNING_RATE"_"weight_decay_$SELECTOR_WEIGHT_DECAY"
          EXTRA_ARGS="--learnedfeat-selector-depth $SELECTOR_DEPTH --learnedfeat-selector-hidden-channels $SELECTOR_HIDDEN_CHANNELS --learnedfeat-selector-dropout $SELECTOR_DROPOUT --learnedfeat-selector-lr $SELECTOR_LEARNING_RATE --learnedfeat-selector-weight-decay $SELECTOR_WEIGHT_DECAY"
          SELECTOR_CACHE_DIR="learnedfeat_sets/$DESIGN_TAG"
          LOG_ROOT="$PROJECT_ROOT/logs/learnedfeat_4gpu/$STAMP/$DESIGN_TAG"
          export SELECTOR_CACHE_DIR EXTRA_ARGS LOG_ROOT
          bash "$PROJECT_ROOT/scripts/evaluator_batch.sh"
        done
      done
    done
  done
done
