#!/bin/sh
set -e
PROJECT_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

GPUS="0 1 2"
DATASETS="facebook"
MODELS="mf mlp ppr concat gcn gat sage gae seal buddy neo-gnn ncn ncnc nbfnet peg lpformer n2v"
RUNS="1 2 3"
MLP_SELECTOR_DEPTHS="2 3"
MLP_SELECTOR_HIDDEN_CHANNELS="256"
MLP_SELECTOR_DROPOUTS="0.1"
MLP_SELECTOR_LEARNING_RATES="0.01"
MLP_SELECTOR_WEIGHT_DECAYS="0"
HEURISTICS="all"
SPLIT="test"
TEST_POSITIVE_CAP="10000"
COMPUTE_AUC="no"
MLP_NEGATIVES="500"

MLP_SCORE_BATCH_SIZE="65536"
MLP_SELECTOR_SEED="0"
MLP_SELECTOR_EPOCHS="500"
MLP_SELECTOR_EVAL_STEPS="5"
MLP_SELECTOR_PATIENCE="10"
MLP_SELECTOR_BATCH_SIZE="1024"
MLP_SELECTOR_METRIC=""
MLP_SELECTOR_TRAINING_TAG="strict_bce_fixed_250_neutral_validation_v1"
EVALUATOR_MODULE="eval_modes.mlp_mode"
SELECTOR_POLICY="mlp"
CANDIDATE_POLICY="$SELECTOR_POLICY"
EVALUATION_LABEL="$SELECTOR_POLICY"
SELECTOR_CHECKPOINT_MODEL=""
SELECTOR_CHECKPOINT_ROOT=""
SELECTOR_CHECKPOINT_RUN=""
SELECTOR_NEGATIVES="$MLP_NEGATIVES"
SELECTOR_SCORE_BATCH_SIZE="$MLP_SCORE_BATCH_SIZE"
SELECTOR_SEED="$MLP_SELECTOR_SEED"
SELECTOR_EPOCHS="$MLP_SELECTOR_EPOCHS"
SELECTOR_EVAL_STEPS="$MLP_SELECTOR_EVAL_STEPS"
SELECTOR_PATIENCE="$MLP_SELECTOR_PATIENCE"
SELECTOR_BATCH_SIZE="$MLP_SELECTOR_BATCH_SIZE"
SELECTOR_METRIC="$MLP_SELECTOR_METRIC"
DATA_ROOT="dataset"
CHECKPOINT_ROOT="checkpoints"
TARGET_CHECKPOINT_MODE="heart"
EDGE_BATCH_SIZE="0"
NODE_CHUNK_SIZE="0"
COMPARISON_BATCH_SIZE="256"
SOURCE_BATCH_SIZE=""
QUIET="0"
DRY_RUN="0"
POLL_SECONDS="1"

STAMP="$(date +%Y%m%d_%H%M%S)_$$"
for SELECTOR_HIDDEN_CHANNELS in $MLP_SELECTOR_HIDDEN_CHANNELS
do
  case "$SELECTOR_HIDDEN_CHANNELS" in
    ""|*[!0-9]*|0)
      echo "MLP_SELECTOR_HIDDEN_CHANNELS must contain positive integers." >&2
      exit 2
      ;;
  esac
  for SELECTOR_DEPTH in $MLP_SELECTOR_DEPTHS
  do
    case "$SELECTOR_DEPTH" in
      ""|*[!0-9]*|0)
        echo "MLP_SELECTOR_DEPTHS must contain positive integers." >&2
        exit 2
        ;;
    esac
    for SELECTOR_DROPOUT in $MLP_SELECTOR_DROPOUTS
    do
      for SELECTOR_LEARNING_RATE in $MLP_SELECTOR_LEARNING_RATES
      do
        for SELECTOR_WEIGHT_DECAY in $MLP_SELECTOR_WEIGHT_DECAYS
        do
          DEPTH_TAG="selector_depth_$SELECTOR_DEPTH"
          HIDDEN_TAG="hidden_$SELECTOR_HIDDEN_CHANNELS"
          DESIGN_TAG="$DEPTH_TAG"_"$HIDDEN_TAG"_"dropout_$SELECTOR_DROPOUT"_"lr_$SELECTOR_LEARNING_RATE"_"weight_decay_$SELECTOR_WEIGHT_DECAY"_"$MLP_SELECTOR_TRAINING_TAG"
          EXTRA_ARGS="--mlp-selector-depth $SELECTOR_DEPTH --mlp-selector-hidden-channels $SELECTOR_HIDDEN_CHANNELS --mlp-selector-dropout $SELECTOR_DROPOUT --mlp-selector-lr $SELECTOR_LEARNING_RATE --mlp-selector-weight-decay $SELECTOR_WEIGHT_DECAY"
          MLP_CACHE_DIR="mlp_sets/$DESIGN_TAG"
          SELECTOR_CACHE_DIR="$MLP_CACHE_DIR"
          LOG_ROOT="$PROJECT_ROOT/logs/mlp_4gpu/$STAMP/$DESIGN_TAG"
          export GPUS DATASETS MODELS RUNS HEURISTICS SPLIT TEST_POSITIVE_CAP COMPUTE_AUC
          export EVALUATOR_MODULE CANDIDATE_POLICY EVALUATION_LABEL SELECTOR_POLICY SELECTOR_CHECKPOINT_MODEL SELECTOR_CHECKPOINT_ROOT SELECTOR_CHECKPOINT_RUN TARGET_CHECKPOINT_MODE
          export SELECTOR_NEGATIVES SELECTOR_CACHE_DIR SELECTOR_SCORE_BATCH_SIZE SELECTOR_SEED SELECTOR_EPOCHS SELECTOR_EVAL_STEPS SELECTOR_PATIENCE SELECTOR_BATCH_SIZE SELECTOR_METRIC
          export DATA_ROOT CHECKPOINT_ROOT EDGE_BATCH_SIZE NODE_CHUNK_SIZE COMPARISON_BATCH_SIZE SOURCE_BATCH_SIZE EXTRA_ARGS QUIET DRY_RUN POLL_SECONDS LOG_ROOT
          bash "$PROJECT_ROOT/scripts/evaluator_batch.sh" "$@"
        done
      done
    done
  done
done
